### PR TITLE
Fix tare bug with raw readings, add error state when reading before ready

### LINKED ISSUE #1: Issue with multiple tarings
Hey there! Thanks a bunch for this library, it fits exactly what I needed.

I noticed a little problem, when calling the `tare()` function multiple times. It seems you use `read()` to get the value to be put as the offset, but `read()` itself already accounts for any previously existing `offset`.

So when performing the second tare, the weight is not reset to zero. Hope this makes sense!
You probably need a function that can get you the raw reading without applying the offset. Maybe the offset should only be applied in the `read_scaled()` function.

Thanks again!

PS: are you open to contributions?

### PR DESCRIPTION
**Pull request by DaneSlattery**
Address (https://github.com/DaneSlattery/hx711/issues/1)

Address TODO in comments.

### CODE REVIEW

**Comment by beeb** [comment]
Thanks for the quick fix!

Is it possible to implement or derive `core::fmt::Debug` and `core::fmt::Display` for the new error struct? That would allow to easily print the error variant in case of error.

Would it also make sense to derive the `Error` trait? Not sure what's recommended for embedded libraries.

**Comment by DaneSlattery** [comment]
> Thanks for the quick fix!
> 
> Is it possible to implement or derive `core::fmt::Debug` and `core::fmt::Display` for the new error struct? That would allow to easily print the error variant in case of error.

Done.


> 
> Would it also make sense to derive the `Error` trait? Not sure what's recommended for embedded libraries.

The error trait seems to be unstable for the `core` standard library. Seems like the default approach for embedded is to rely on the specific error handler to deal with inner details. [https://esp-rs.github.io/no_std-training/03_1_panic.html](https://esp-rs.github.io/no_std-training/03_1_panic.html)

**Comment by DaneSlattery** [comment]
@beeb  are you using this library from crates.io? Perhaps I should release another version.

**Comment by beeb** [comment]
For testing I'm now including the version from this branch, and happy to report that everything seems to work. I get some weird glitches from time to time on 2 different amplifiers but not sure if that's the library's fault. Need to investigate more. It was already happening before with the version from crates.io so not related to those changes.

**Comment by beeb** [comment]
Lgtm

**Review by beeb — APPROVED** [review]

**Pull request merged**
